config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :commerces, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commerce.rb
class Commerce < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commerces_controller.rb
class CommercesController < ApplicationController
  def index
    @commerces = Commerce.all
  end

  def destroy
    @commerce.destroy
    redirect_to dashboard_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/commerces/index.html.erb
<h1 style="font-weight: 800">Tous les commerces</h1>
<div class="centering">
  <div class="shop-grid">
    <% @commerces.each do |commerce| %>
      <div class="shop-card">
        <div class="top-card">
          <p class="name"><%= commerce.name %></p>
          <p class="tag"><%= commerce.tag %></p>
        </div>
        <img src="https://images.unsplash.com/photo-1472851294608-062f824d29cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="">
        <p class="description"><%= commerce.description %></p>
        <div class="centering">
          <a class="site-button" href="#">Vers le site</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solidile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <div class="content-wrapper" style="min-height: calc(100vh - 68px - 100px)">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="left-banner">
    <div class="text-content">
      <h1>Bienvenue sur Solid' île !</h1>
      <p>Solid' île est LA plateforme pour soutenir les commerçants de Belle-Île-En-Mer en cette période où nombre d'entre eux sont contraints de fermer. Profitez-en pour acheter local et préparer les cadeaux de Noël à l'avance !</p>
      <%= link_to "Tous les commerçants", commerces_path, class: "site-button" %>
    </div>
  </div>
  <img src="https://images.unsplash.com/photo-1589211188290-afeb38d1a655?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1953&q=80" alt="">
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="left">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="logo">
        <h1>Solid'île</h1>
      </div>
    <% end %>
  </div>



  <div class="right">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <ul class="navbar-nav mr-auto">
      <div class="general">
        <li class="nav-item active">
          <%= link_to "Tous les commerçants", commerces_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Produits locaux", "#", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Décoration", "#", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Gastronomie", "#", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Mode", "#", class: "nav-link" %>
        </li>
         <li class="nav-item active">
          <%= link_to "Enfants", "#", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Papeterie", "#", class: "nav-link" %>
        </li>

      </div>
    </ul>
  </div>
</div>